name: Android CI

on:
  push:
    paths-ignore: # 有時候不想要改個文档也触发 github actions
      - '**.md'
      - 'LICENSE'
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Java Version
        run: java --version
      - name: Build with Gradle
        run: ./gradlew build
